CREATE TABLE groupMembers (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    GroupID INTEGER,
    UserID INTEGER,
    FOREIGN KEY (GroupID) REFERENCES Groups(Id),
    FOREIGN KEY (UserID) REFERENCES User(Id)
);
